### ISSUE TITLE
Arithmetic operation resulted in an overflow in mp3.GetTag

### ISSUE THREAD

**Issue by iqmeta** [JeevanJames/Id3#66]
![image](https://github.com/JeevanJames/Id3/assets/7533842/a2ed5256-8438-4194-881c-a4b4d6878b16)

   at Id3.TextEncodingHelper.GetSplitterBytes(Id3TextEncoding encodingType)
   at Id3.v2.Id3V23Handler.DecodePicture(Byte[] data)
   at Id3.v2.Id3V23Handler.ReadTag(Stream stream, Object& additionalData)
   at Id3.Mp3.GetTag(Id3TagFamily family)
   at Program.<<Main>$>g__readFile|0_0(String musicFile) in C:\Temp\fixMp3\Program.cs:line 9
   at Program.<Main>$(String[] args) in C:\Temp\fixMp3\Program.cs:line 35

**Comment by czf** [comment]
also ran into this issue.  I clone the repo to see what was going on locally and just added some encoding options
https://github.com/czf/Id3/pull/1/files#diff-0f7318c42a4fc66925efd21803b659ff7ada3f6193523981160d9c23ac0412af

I'm able to get past the exception and the tags I'm updating are reflected
